config/routes.rb
Rails.application.routes.draw do
  
  # Landing Page
  root 'landing#index'

  # Route for Devise
  devise_for :users

  # Route for Users to redirect to Profiles
  resources :users, only: [:show, :update], controller: :profiles

  # Route for Profiles
  resource :profile

  # Route for Photos and Comments
  resources :photos do
    resources :comments
  end
  
  # Route for Top 10 Trending Users
  get 'trending_users/index', as: "trending_users"
  
  # Route for Feed
  # get 'feed/index'
  get '/feed' => 'feed#index', as: "feed"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy] # Still allow users to see page if not signed in except for edit, update, delete
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    redirect_to edit_profile_url if @profile.nil?
  end

  # GET /profiles/1/edit
  def edit
    # Perform new profile creation if it doesn't exist. Otherwise, edits the profile
    # @profile = Profile.find_or_initialize_by(user: current_user)

    # Have blank profile if the user hasn't created one yet for their account
    @profile = Profile.new(user: current_user) if @profile.nil?
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|

      # User performs follow / unfollow
      if performing_follow?
        @profile.user.toggle_followed_by(current_user)
        format.html { redirect_to @profile.user }
        format.json { render :show, status: :ok, location: @profile }

      # One does not simply edit the profile of another user
      elsif @profile.nil? || @profile.user != current_user
        redirect_to root_url

      # User updates his profile
      elsif @profile.update(profile_params)
        format.html { redirect_to profile_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }

      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      # Looking at someone else’s profile
      if params[:id]
        # @profile = Profile.find(params[:id])
        @profile = Profile.find_by!(user_id: params[:id])
      # Current user’s profile
      else
        @profile = Profile.find_by(user: current_user)
        # @profile = Profile.find_by!(user: current_user)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :name, :bio)
    end

    def performing_follow?
      # params.require(:user)[:follow].present?
      # if params[:user]
      #   params.require(:user)[:follow].present?
      # else
      #   params.require(:profile)[:follow].present?
      # end

      # params[:user] ? params.require(:user)[:follow].present? : params.require(:profile)[:follow].present?
      # params.require( params[:user] ? :user : :profile )[:toggle_follow].present?
      params.dig(:user, :toggle_follow).present?
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, url: profile_path, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :profile_username %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :profile_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.name %></td>
        <td><%= profile.bio %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit Profile', edit_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profile_path %>

app/views/profiles/show.html.erb
<nav class="navbar justify-content-center">
  <h1>
    <%= @profile.username %>
  </h1>
</nav>

<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h3><%= @profile.name %></h3>
  <p>
    <%= @profile.bio %>
  </p>

  <div class="d-flex justify-content-around">
    <p class="profile-count text-center">
      <%= pluralize(@profile.user.photos.count, 'photo') %>
    </p>
    <p class="profile-count text-center">
      <%= pluralize(@profile.user.followers.count, 'follower') %>
    </p>
    <p class="profile-count text-center">
      <%= pluralize(@profile.user.following.count, 'following', plural: 'following') %>
    </p>
  </div>

  <% if user_signed_in? %>
    <% if @profile.user == current_user %>
      <%= link_to 'Edit', edit_profile_path, class: 'btn btn-secondary btn-block' %>
    <% else %>
      <%= form_with(model: @profile.user, method: :patch) do |f| %>
        <%= f.hidden_field :toggle_follow, value: true %>
        <%= f.submit @profile.user.followed_by?(current_user) ? 'Unfollow' : 'Follow', class: 'btn btn-primary btn-block' %>
        <% end %>
    <% end %>

    <!-- Show Grid of Photos -->

    <div class="photo-grid">
      <% @profile.user.photos.each do |photo| %>
        <%= link_to image_tag(photo.image_url), photo %>
      <% end %>
    </div>
  <% end %>

  <nav class="secondary-nav">
    <br><br>
    <%= link_to 'Back', :back, class: 'btn btn-primary'%>
    <%= link_to 'View Trending Users', trending_users_path, class: 'btn btn-primary'%>
  </nav>
  
</div>