config/routes.rb
Rails.application.routes.draw do
  
  # Landing Page
  root 'landing#index'

  # Route for Devise
  devise_for :users

  # Route for Users to redirect to Profiles
  resources :users, only: [:show, :update], controller: :profiles

  # Route for Profiles
  resource :profile

  # Route for Photos and Comments
  resources :photos do
    resources :comments
  end
  
  # Route for Top 10 Trending Users
  get 'trending_users/index', as: "trending_users"
  
  # Route for Feed
  # get 'feed/index'
  get '/feed' => 'feed#index', as: "feed"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_photo

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @new_comment = Comment.new
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.photo = @photo
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to photo_comments_url(@photo), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: [@photo, @comment] }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to photo_comments_url(@photo), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: [@photo, @comment] }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to photo_comments_url(@photo), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_photo
      @photo = Photo.find(params[:photo_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:photo_id, :user_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div>
  <p>
    <strong><%= comment.user.email %></strong>
    <%= comment.content %>
  </p>
  <td><%= link_to 'Edit', edit_photo_comment_path(photo, comment) %></td>
  <td><%= link_to 'Destroy', [photo, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@photo, comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<nav class="navbar">
  <%= link_to 'Back', photo_path(@photo) %>
  <h1>Comments</h1>
</nav>

<p id="notice"><%= notice %></p>

<section>
  <%= render @comments, photo: @photo %>
</section>

<%= render 'form', comment: @new_comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @comment.photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>