config/routes.rb
Rails.application.routes.draw do
  
  # Landing Page
  root 'landing#index'

  # Route for Devise
  devise_for :users

  # Route for Users to redirect to Profiles
  resources :users, only: [:show, :update], controller: :profiles

  # Route for Profiles
  resource :profile

  # Route for Photos and Comments
  resources :photos do
    resources :comments
  end
  
  # Route for Top 10 Trending Users
  get 'trending_users/index', as: "trending_users"
  
  # Route for Feed
  # get 'feed/index'
  get '/feed' => 'feed#index', as: "feed"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <h1 class="mt-3">Instarails</h1>
      <img src="<%= asset_url('3q3a0859.jpg') %>" class="img-fluid">
    </div>
    <div class="col">
      <h2 class="mt-3">The number two photo social app</h2>
      <nav>
        <% if user_signed_in? %>
          <%= link_to 'Edit account', edit_user_registration_path, class: 'btn btn-primary' %>
          <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-light', method: :delete %>
          <br><br>
          <%= link_to 'View Profile', profile_path, class: 'btn btn-success' %>
          <%= link_to 'View Trending Users', trending_users_path, class: 'btn btn-success'%>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
        <% end %>
      </nav>
    </div>
  </div>
</div>