config/routes.rb
Rails.application.routes.draw do
  
  # Landing Page
  root 'landing#index'

  # Route for Devise
  devise_for :users

  # Route for Users to redirect to Profiles
  resources :users, only: [:show, :update], controller: :profiles

  # Route for Profiles
  resource :profile

  # Route for Photos and Comments
  resources :photos do
    resources :comments
  end
  
  # Route for Top 10 Trending Users
  get 'trending_users/index', as: "trending_users"
  
  # Route for Feed
  # get 'feed/index'
  get '/feed' => 'feed#index', as: "feed"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader::Attachment.new(:image)

  belongs_to :user
  has_and_belongs_to_many :likers, class_name: 'User', join_table: :likes
  has_many :comments

  def liked_by?(user)
    likers.exists?(user.id)
  end

  def toggle_liked_by(user)
    if likers.exists?(user.id)
      likers.destroy(user)
    else
      likers << user
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if is_liking?
        @photo.toggle_liked_by(current_user)
        # format.html { redirect_to @photo }
        format.html { redirect_to request.referrer }        
        format.json { render :show, status: :ok, location: @photo }
      elsif current_user == @photo.user
        if @photo.update(photo_params)
          format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
          format.json { render :show, status: :ok, location: @photo }
        else
          format.html { render :edit }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :description)
    end

    def is_liking?
      params.require(:photo)[:liked].present?
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :photo_image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :photo_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<p>
    <%= image_tag photo.image.url, class: 'img-fluid', width: 800 %>
</p>

<p>
    <strong><%= photo.user.email %></strong>
    <%= photo.description %>
</p>

<% if user_signed_in? %>
    <!-- Like button -->
    <%= form_with model: photo, method: :patch do |f| %>
    <% liked = photo.liked_by?(current_user) %>
    <%= f.hidden_field :liked, value: liked %>
    <%= f.button liked ? 'Unlike' : 'Like', class: 'btn btn-secondary' %>
    <%= link_to 'Comments', photo_comments_path(photo), class: 'btn btn-secondary' %>
    <% end %>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<nav class="nav sticky-top justify-content-center pt-2 pb-2 bg-light">
  <%= link_to 'New Photo', new_photo_path, class: 'btn btn-primary' %>
</nav>

<p id="notice"><%= notice %></p>

<section>
  <% @photos.each do |photo| %>
    <article>
      <%= link_to photo do %>
        <figure>
          <%= image_tag photo.image.url, class: 'img-fluid', alt: photo.description %>
        </figure>
      <% end %>
      <p>
        <strong><%= photo.user.email %></strong>
        <%= photo.description %>
      </p>
    </article>
  <% end %>
</section>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @photo %>

<section>
  <%= render @photo.comments, photo: @photo %>
</section>

<% if current_user == @photo.user %>
  <%= link_to 'Edit', edit_photo_path(@photo) %> ·
  <%= link_to 'Destroy', @photo, method: :delete, data: { confirm: 'Are you sure?' } %> ·
<% end %>
<%= link_to 'Back', :back %>